let jokes = ["There are 2 types of people: those who can extrapolate from incomplete data sets...",
    "If you play a Windows CD backwards, you\'ll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.",
    "Number of days since I have encountered an array index error: -1.",
    "If you listen to a UNIX shell, can you hear the C?",
    "A programmer walks into a bar and orders 1.38 root beers. The bartender informs her it\'s a root beer float. She says \'Make it a double!\'",
    "A COBOL programmer makes millions with Y2K remediation and decides to get cryogenically frozen. \"The year is 9999. You know COBOL, right?\"",
    "I\'ve been using Vim for a long time now, mainly because I can\'t figure out how to exit.",
    "Speed dating is useless. 5 minutes is not enough to properly explain the benefits of the Unix philosophy.",
    "Windows is NOT a virus. Viruses DO something.",
    "What\'s the object-oriented way to become wealthy? Inheritance.",
    "I would tell you a joke about UDP, but you would never get it.",
    "I have a joke on programming but it only works on my computer.",
    "!false, (It\'s funny because it\'s true)",
    "There are 10 types of people: those who understand binary, those who don\'t, and those who were expecting this joke to be in trinary.",
    "What does pyjokes have in common with Adobe Flash? It gets updated all the time, but never gets any better.",
    "Learning JavaScript is like looking both ways before you cross the street, and then getting hit by an airplane.",
    "Sympathy for the Devil is really just about being nice to QAs.",
    "A programmer had a problem. He thought to himself, \'I know, I\'ll solve it with threads!\'. has Now problems. two he",
    "Computer analyst to programmer: You start coding. I\'ll go find out what they want.",
    "Why do you always use i and j variales in loops? It\'s the law......",
    "Pirates go \'arg!\', computer pirates go \'argv!\'",
    "Why don\'t jokes work in octal? Because 7 10 11.",
    "There are only two hard problems in Computer Science: cache invalidation, naming things and off-by-one-errors.",
    "I love pressing the F5 key. It\'s refreshing.",
    "Don\'t compute and drive; the life you save may be your own.",
    "A programmer walks into a foo...",
    "When Apple employees die, does their life HTML5 in front of their eyes?",
    "Bug? That\'s not a bug, that\'s a feature.",
    "I had a problem so I thought I\'d use Java. Now I have a ProblemFactory.",
    "Have you heard about the new Cray super computer? It\'s so fast, it executes an infinite loop in 6 seconds.",
    "Java: Write once, run away.",
    "Why do Java programmers have to wear glasses? Because they don\'t C#.",
    "Software developers like to solve problems. If there are no problems handily available, they will create their own.",
    "\'Knock, knock.\' \'Who's there?\' ... very long pause ... \'Java.\'",
    "Software salesmen and used-car salesmen differ in that the latter know when they are lying.",
    "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl.",
    "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
    "Triumphantly, Beth removed Python 2.7 from her server in 2030. \'Finally!\' she said with glee, only to see the announcement for Python 4.4.",
    "The program is absolutely right; therefore the computer must be wrong.",
    "You never finish a program, you just stop working on it.",
    "There are II types of people: Those who understand Roman Numerals and those who don\'t.",
    "You don\'t have to know how the computer works, just how to work the computer.",
    "How many Prolog programmers does it take to change a lightbulb? false.",
    "The computer is mightier than the pen, the sword, and usually, the programmer",
    "Why was the developer bankrupt? He\'d used all his cache.",
    "Speed Kills! Use Windows.",
    "Number of days since I have encountered an off-by-one error: 0.",
    "Computer programmers do it byte by byte.",
    "QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.",
    "A Programmer was walking out of door for work, his wife said \"while you\'re out, buy some milk\" and he never returned.",
    "Waiter: He\'s choking! Is anyone a doctor? Programmer: I\'m a Vim user.",
    "Beware of programmers that carry screwdrivers.",
    "Unix is user friendly. It\'s just very particular about who its friends are.",
    "Are you a RESTful API? because you GET my attention, PUT some love, POST the cutest smile, and DELETE my bad day.",
    "If at first you don\'t succeed, call it version 1.0.",
    "Hey! It compiles! Ship it!",
    "The box said: \'install on Windows 95, NT 4.0 or better\'. So I installed it on Linux.",
    "A QA engineer walks into a bar. Runs into a bar. Crawls into a bar. Dances into a bar. Tiptoes into a bar. Rams a bar. Jumps into a bar.",
    "To understand recursion you must first understand recursion.",
    "Why do programmers confuse Halloween with Christmas? Because OCT 31 == DEC 25.",
    "Eight bytes walk into a bar. The bartender asks, \'Can I get you anything?\' \'Yeah,\' replies the bytes. \'Make us a double.\'",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "All programmers are playwrights, and all computers are lousy actors.",
    "When your hammer is C++, everything begins to look like a thumb.",
    "Never say \'OOPS!\' always say \'Ah, Interesting!\'",
    "A: What is your address? Me: 173.168.15.10 A: No, your local address Me: 127.0.0.1 A: I mean your physical address B: 29:01:38:62:31:58",
    "What do you call a programmer from Finland? Nerdic.", "Why do sin and tan work? Just cos.",
    "My attitude isn\'t bad. It\'s in beta.",
    "Microsoft hold a bi-monthly internal \"productive week\" where they use Google instead of Bing.",
    "ASCII stupid question, get a stupid ANSI.",
    "Writing PHP is like peeing in the swimming pool, everyone did it, but we don\'t need to bring it up in public.",
    "I haven\'t lost my mind; it\'s backed up on tape somewhere.",
    "C and C++ went to a five star bar, C was stopped by the gate guards because C got no class.",
    "Two bytes meet. The first byte asks, \"Are you ill?\"<br>The second byte replies, \"No, just feeling a bit off.\"",
    "\"Knock knock!\"<br>\"Who is there?\"<br>\"Yah!\"<br>\"Yah, who?\"<br>\"No not Yahoo, Google.\"",
    "What does the R in Recursion stand for?<br>Recursion.",
    "How did the first program die?<br>It was executed.",
    "What is the difference between C++ and C?<br>Just 1.",
    "What do you call when 8 mosquitos bit you?<br>A mosquito byte.",
    "She: What can you do for me?<br>Me: Umm.. I can say I love you in 20 languages! (Programming languages)",
    "WINDOWS: Will Install Needless Data On Whole System.<br>IBM: I Blame Microsoft.<br>MICROSOFT: Most Intelligent Customers Realize Our Software Only Fools Teenagers.",
    "Why don\'t A.I. engineers need a resume?<br>They just let their projects speak for themselves.",
    "Programming is like sex, One mistake and you have to support it for the rest of your life.",
    "Normal People: log kya kahenge<br>Developers: console.log kya kahenge",
    "What is the Bollywood equivalent of Recursion?<br>Karthik calling Karthik."];
let joke_placeholder = document.getElementById("joke-placeholder");
let joke_button = document.getElementById("new-joke-button");
joke_placeholder.innerHTML = jokes[Math.floor(Math.random() * 86) + 1];
joke_button.addEventListener("click", function() {
    joke_placeholder.innerHTML = jokes[Math.floor(Math.random() * 86) + 1];
});